import numpy as np

MAP_TITLE = {
    "Ingenieur": np.nan,
    "Dr. med.": "Dr.",
    "nan": np.nan,
    "Baron": np.nan,
    "Rechtsanwalt": np.nan,
    "Professor": "Prof.",
    "Baroness": np.nan,
    "Gräfin": np.nan,
    "Graf": np.nan,
    "Freifrau": np.nan,
    "Freiherr": np.nan,
    "Ritter": np.nan,
    "Prinzessin": np.nan,
    "Edler": np.nan,
    "Dr. Ing.": "Dr.",
    "Prof. Dr. med.": "Prof. Dr.",
    "Prof. Dr. Dr.": "Prof. Dr.",
    "Dr. Dr.": "Dr.",
    "Dr. mult.": "Dr.",
    "Dr. med": "Dr.",
    "Dr. h.c.": "Dr.",
    "Prof. Dr. med.": "Prof. Dr.",
    "Prof. Dr. Dr. h. c.": "Prof. Dr.",
    "Dr. Ingenieur": "Dr.",
    "Botschafter": np.nan,
    "Dr. Graf": "Dr.",
    "Prof. Dr. Ingenieur": "Prof. Dr.",
    "Exzellenz": np.nan,
    "Dr. Ing. Ingenieur": "Dr.",
    "Dr. Baron": "Dr.",
    "Notar": np.nan,
    "Professor Dr.": "Prof. Dr.",
    "Professor Dr. Ing.": "Prof. Dr.",
    "Hauptmann": np.nan,
}

MAP_GENDER = {
    "männlich": "Herr",
    "weiblich": "Frau",
    "Freiherr": "Herr",
    "Freifrau": "Frau",
}

MAP_REV_MEDIAN = {
    "00": np.nan,
    "01": 0.130,
    "02": 0.170,
    "03": 0.270,
    "04": 0.630,
    "05": 1.935,
    "06": 5.720,
    "07": 30.000,
    "08": 78.316,
    "09": 670.832,
}

MAP_EMPL_MEDIAN = {
    "00": np.nan,
    "01": 2,
    "02": 6,
    "03": 12,
    "04": 26,
    "05": 61,
    "06": 121,
    "07": 251,
    "08": 590,
    "09": 1146,
    "10": 2320,
}