COLUMN_MAPPING = {
    "DunBradstreet": {
        "table_name": "T_DNB_RAW",
        "BisnodeID": "FIRMENNUMMER",
        "Status": "STATUS",
        "Firmenname": "FIRMENNAME",
        "Firmentype": "FIRMENTYP_LANGTEXT",
        "Handelsname": "HANDELSNAME",
        "DUNS_Nummer": "DNB_D_U_N_S_NUMMER",
        "PLZ": "PLZ_STRASSE",
        "Ort": "ORT_STRASSE",
        "Strasse": "STRASSE",
        "Hausnummer": "HAUSNUMMER",
        "Bundesland": "BUNDESLAND",
        "GKZ": "GKZ",
        "Vorwahl_Telefon": "VORWAHL_TELEFON",
        "Telefon": "TELEFON",
        "Umsatz": "UMSATZ",
        "Umsatz_Jahr": "UMSATZ_JAHR",
        "Segment": "SEGMENT_DICC",
        "Marketable": "MARKETABLE",
        "Hauptbranche": "HAUPTBRANCHE_08",
        "Hauptbranchentext": "HAUPTBRANCHENTEXT_08",
        "Nebenbranche": "NEBENBRANCHE_08",
        "Anzahl_Niederlassungen": "ANZAHL_NIEDERLASSUNGEN",
        "Anzahl_Konzernmitglieder": "ANZAHL_KONZERNMITGLIEDER",
        "Beschaeftigte": "BESCHAEFTIGTE",
        "Direkte_Mutter_Nummer": "DIREKTE_MUTTER_NUMMER",
        "Direkte_Mutter_Land": "DIREKTE_MUTTER_LAND",
        "HNR": "HoechsteMutterNummer_0",
        "Rechtsform": "RECHTSFORM_TEXT",
        "Ehemaliger_Firmenname": "EHEMALIGER_FIRMENNAME",
        "Register": "HANDELSREGISTER",
    }
}
