COLUMN_MAPPING = {
    "DunBradstreet": {
        "T_DNB_RAW": "table_name",
        "FIRMENNUMMER": "BisnodeID",
        "STATUS": "Status",
        "FIRMENNAME": "Firmenname",
        "FIRMENTYP_LANGTEXT": "Firmentype",
        "HANDELSNAME": "Handelsname",
        "DNB_D_U_N_S_NUMMER": "DUNS_Nummer",
        "PLZ_STRASSE": "PLZ",
        "ORT_STRASSE": "Ort",
        "STRASSE": "Strasse",
        "HAUSNUMMER": "Hausnummer",
        "BUNDESLAND": "Bundesland",
        "GKZ": "GKZ",
        "VORWAHL_TELEFON": "Vorwahl_Telefon",
        "TELEFON": "Telefon",
        "UMSATZ": "Umsatz",
        "UMSATZ_JAHR": "Umsatz_Jahr",
        "SEGMENT_DICC": "Segment",
        "MARKETABLE": "Marketable",
        "HAUPTBRANCHE_08": "Hauptbranche",
        "HAUPTBRANCHENTEXT_08": "Hauptbranchentext",
        "NEBENBRANCHE_08": "Nebenbranche",
        "ANZAHL_NIEDERLASSUNGEN": "Anzahl_Niederlassungen",
        "ANZAHL_KONZERNMITGLIEDER": "Anzahl_Konzernmitglieder",
        "BESCHAEFTIGTE": "Beschaeftigte",
        "DIREKTE_MUTTER_NUMMER": "Direkte_Mutter_Nummer",
        "DIREKTE_MUTTER_LAND": "Direkte_Mutter_Land",
        "HoechsteMutterNummer_0": "HNR",
        "RECHTSFORM_TEXT": "Rechtsform",
        "EHEMALIGER_FIRMENNAME": "Ehemaliger_Firmenname",
        "HANDELSREGISTER": "Register",
    }
}
